#ifndef _NRF52840_S140_MEMMAP_H
#define _NRF52840_S140_MEMMAP_H

#include "nrf_mbr.h"
#include "nrf_sdm.h"

/* Shared Bootloader Sections */

// nRF52840 Bootloader Settings 4KB
#define BOOTLOADER_SETTINGS_START	(0xFF000)
#define BOOTLOADER_SETTINGS_END		(0x100000)
#define BOOTLOADER_SETTINGS_MAX_SIZE	(BOOTLOADER_SETTINGS_END - BOOTLOADER_SETTINGS_START)

// nRF52840 Bootloader MBR Parameter Storage 4KB
#define BOOTLOADER_MBRPARAM_START	(0xFE000)
#define BOOTLOADER_MBRPARAM_END		(0xFF000)
#define BOOTLOADER_MBRPARAM_MAX_SIZE	(BOOTLOADER_MBRPARAM_END - BOOTLOADER_MBRPARAM_START)

// nRF52840 Bootloader Application Region including MBR Param 56KB
#define BOOTLOADER_REGION_START		(0xF0000)
#define BOOTLOADER_REGION_END		(0xFE000)
#define BOOTLOADER_MAX_SIZE			(BOOTLOADER_REGION_END - BOOTLOADER_REGION_START)

/* SoftDevice Dependant Sections */

// nRF52840 Application Area 804KB
#define APPLICATION_ADDRESS_START   SD_ADDRESS_END
#define APPLICATION_ADDRESS_END		BOOTLOADER_REGION_START
#define APPLICATION_MAX_SIZE		(APPLICATION_ADDRESS_END - APPLICATION_ADDRESS_START)

// nRF52840 Softdevice Area 156KB
#define SD_ADDRESS_START			MBR_END
#define SD_ADDRESS_END				(0x26000)
#define SD_MAX_SIZE					(SD_ADDRESS_END - SD_ADDRESS_START)

/* nRF52840 MBR Section 4KB */

#define MBR_START (0)
#define MBR_END (0x1000)
#define MBR_MAX_SIZE (MBR_END - MBR_START)

/* nRF52840 FLASH */

// 1024KB / 4KB Pages / 512B Blocks
#define NRF52840_FLASHSIZE			(1024 * 1024)
#define NRF52840_PAGESIZE			(4096)
#define NRF52840_BLOCKSIZE			(512)
#define FIRMWARE_LAST_BLOCK_INDEX	(1920 * 512) // 4096 byte sectors, 1920 is bootloader

#endif // _NRF52840_S140_MEMMAP_H
